version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data



  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  user-backend:
    build: ./Users
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8001:8001"

volumes:
  db-data:
  redis-data:
